### PR TITLE
Increase code coverage by fixing things and removing files from coverage

### LINKED ISSUE #431: Increase coverage for like the project
**Please give a one-sentence summary of the cleanup you would like done.**
Increase the coverage for the project by omitting `tests` directory, omitting the things that aren't unit-tested, and adding more tests.

**Please give as many details as possible about the cleanup or refactoring.**
See above.

**Please list any additional context; in particular, list what areas of the code base this would affect.**
Like, most of it that has low coverage percentage.

### PR DESCRIPTION
**Pull request by cheukyin699**
# Pull Request

## Description

**Give a brief description of your changes:** Increase code coverage by adding more tests and removing irrelevant files from coverage.

## Ticket(s)

Closes #431 
Affects #314

### CODE REVIEW

File: scripts/build_check.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ pipenv run mypy .
 mdl .
 
 # We use a script to check if dynamodb is running locally
-COV_OPTIONS="--mypy --cov=./ --cov-branch --cov-config .coverageac"
+COV_OPTIONS="--mypy --cov=./ --cov-branch --cov-config .coveragerc"
```
Comment (rmcreyes) [inline scripts/build_check.sh]: 👍
